package parsers;

public enum Parameters {
    PLAYER_TYPE,
    POPULATION,
    SELECTION_LIMIT,

    MUTATION,
    MUTATION_PROB,

    CROSSOVER,
    CROSSOVER_PROB,
    UNIFORM_THRESHOLD,

    SELECTION_METHOD_A,
    SELECTION_METHOD_B,
    SELECTION_METHOD_PROB,

    REPLACEMENT_METHOD_A,
    REPLACEMENT_METHOD_B,
    REPLACEMENT_METHOD_PROB,

    TOURNAMENT_PROB_THRESHOLD,
    TOURNAMENT_DET_M,

    BOLTZMANN_T0,
    BOLTZMANN_TK,

    IMPLEMENTATION_METHOD,

    CRITERIA,
    CRITERIA_PARAM;
}
